aliyun:
  oss:
    accessKeyId: LTAI4GBfAZSSf7c8JhEPbK3r
    accessKeySecred: VpMu3ShYf30IpaMNlhEDe8dzBclVGT
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: aliyun-oss-model
    policyExpire: 300
    maxSize: 20
