apiVersion: v1
kind: Service
metadata:
  name: test-server-prod
  namespace: prod
  labels:
    app: test-server-prod
spec:
  type: NodePort
  ports:
    - port: 10001
      nodePort: 50001 #service对外开放端口
  selector:
    app: test-server-prod
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: test-server-prod #名称
  namespace: prod
  labels:
    app: test-server-prod #标注
spec:
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: test-server-prod
  template:
    metadata:
      labels:
        app: test-server-prod
    spec:
      containers: #docker容器的配置
        - name: test-server-prod
          image: 42.192.222.62:9191/code-galaxy/test-server:latest # pull镜像的地址 ip:prot/dir/images:tag
          imagePullPolicy: IfNotPresent #pull镜像时机，
          ports:
            - containerPort: 10001 #容器对外开放端口,需与springboot配置文件一致
